// src/components/Footer.svelte
<script>
	import AboutButton from "./AboutButton.svelte";
	import Export from "./Export.svelte";
	import SettingsButton from "./SettingsButton.svelte";
	import ThemeSelect from "./ThemeSelect.svelte";
</script>

<footer
	class="fixed bottom-0 h-auto w-screen text-xs px-1 flex justify-between"
>
	<div class="flex gap-1 bg-inherit text-inherit">
		<Export />
	</div>
	<div class="flex gap-1 bg-inherit text-inherit">
		<SettingsButton />
		<AboutButton />
		<ThemeSelect />
	</div>
</footer>

// src/components/Footer.tsx
import React from "react";
import Export from "./footer/Export";
import Theme from "./footer/Theme";
import { ThemeEntry } from "../utilities/UIThemes";
import { AboutButton } from "./About";
import { SettingsButton } from "./Settings";

type Props = {
	text: string;
	saveStatus: boolean;
	UITheme: ThemeEntry;
	setUITheme: (newTheme: string) => void;
};

const Footer = (props: Props) => {
	return (
		<footer className="fixed bottom-0 h-auto w-screen text-xs px-1 flex justify-between">
			{/* left side */}
			<div className="flex gap-1 bg-inherit text-inherit">
				<Export text={props.text} />
			</div>
			{/* right side */}
			<div className="flex gap-1 bg-inherit text-inherit">
				<AboutButton />
				<SettingsButton />
				<Theme setUITheme={props.setUITheme} UITheme={props.UITheme} />
			</div>
		</footer>
	);
};

export default Footer;
